# Generated by Django 6.0 on 2025-12-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineroEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(choices=[('mama', 'Mamá'), ('mauricio', 'Mauricio')], max_length=20)),
                ('monto_euros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_soles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
