# Generated by Django 6.0 on 2025-12-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_dineroenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('falta', 'Falta Pagar'), ('pagado', 'Pagado'), ('no_pago', 'No se Pagó')], default='falta', max_length=20),
        ),
        migrations.AddField(
            model_name='gasto',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
