# Generated by Django 6.0 on 2025-12-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_gasto_estado_gasto_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoAFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='De qué es el gasto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes_afp/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
